name: Deploy Matrix Synapse

on:
  push:
    branches: [ main ]

jobs:
  build-and-run-synapse:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create Docker volumes
        run: docker volume create synapse_data_volume || true

      - name: Remove old containers
        run: docker rm -f synapse synapse-nginx 2>/dev/null || true

      - name: Generate Synapse config
        run: |
          docker run --rm \
            -v synapse_data_volume:/data \
            -e SYNAPSE_SERVER_NAME="${{ secrets.SYNAPSE_SERVER_IP }}" \
            -e SYNAPSE_REPORT_STATS=no \
            matrixdotorg/synapse:latest generate

      - name: Fix ownership
        run: docker run --rm -v synapse_data_volume:/data alpine chown -R 991:991 /data

      - name: Verify Synapse config
        run: docker run --rm -v synapse_data_volume:/data alpine ls -l /data

      - name: Create docker-compose.yml
        run: |
          cat > docker-compose.yml <<EOF
          version: "3.9"
          services:
            synapse:
              image: matrixdotorg/synapse:latest
              container_name: synapse
              restart: unless-stopped
              volumes:
                - synapse_data_volume:/data
              ports:
                - "8008:8008"
            synapse-nginx:
              image: nginx:latest
              container_name: synapse-nginx
              restart: unless-stopped
              ports:
                - "2050:443"
              volumes:
                - ./nginx.conf:/etc/nginx/conf.d/synapse.conf
          volumes:
            synapse_data_volume:
          EOF

      - name: Run Synapse stack
        run: docker compose up -d

      - name: Wait for Synapse to be healthy
        timeout-minutes: 5
        run: |
          until curl -f http://localhost:8008/_matrix/client/versions; do
            echo "Waiting for Synapse to be healthy..."
            sleep 5
          done
          echo "Synapse is healthy!"
